@echo off
echo Generating static site...
call npx nuxi generate
echo Uploading to server...
scp -rp .output/public/* root@toys.cmrn.io:/home/cmrn/voo/vue
echo Done! Opening site...
start "" http://toys.cmrn.io
