@echo off
echo Generating static site...
call npx nuxi generate
echo Uploading to server...
scp -rp .output/public/* root@haha.69.omg.lol:/home/cmrn/voo/vue
echo Done! Opening site...
start "" http://haha.69.omg.lol